Update README.md with Meta and References
oasis-roles/meta_standards pull request #11
Opened 2020-03-11 13:05 UTC by jeffcpullen

Did not include internal RH links since those would be inaccessible by most.

2020-03-11 13:28 UTC, pcahyna commented on README.md
> +
I would move it above, just below the introductory sentence. It is even more basic than the "Basics".

2020-03-11 17:27 UTC, greg-hellings requested changes

2020-03-11 17:27 UTC, greg-hellings commented on README.md
> +A rationale should be included for best practices, with a reference if applicable. It is really helpful to know not only how to do certain things, but why to do them in this way. It will also help wi
Please give some line breaks in this paragraph around the 80-90 character width to facilitate reading and editing in code editors like vim.

2020-03-16 17:57 UTC, pcahyna commented on README.md
> +* https://github.com/oasis-roles/meta_standards
this is too meta

2020-04-01 22:04 UTC, pcahyna commented
Can be closed, in favor of #15

2020-04-08 14:50 UTC, closed without merging