Propose documents be in README.md
oasis-roles/meta_standards pull request #7
Opened 2020-02-05 17:04 UTC by greg-hellings

We have been putting documentation in the README.md for a long time, not
in the {defaults,vars}/main.yml files. We should update our best
practices to reflect this.

2020-02-05 18:17 UTC, tehsmyers requested changes
I love it except for the typo!

2020-02-05 18:17 UTC, seandst commented on README.md
> +  This allows a single place for users to look to see what inputs are expected. Document these varialbes
varialbes!

2020-02-05 19:46 UTC, tehsmyers approved these changes

2020-02-06 16:38 UTC, robled approved these changes

2020-02-06 16:39 UTC, merged